name: easytem
description: Easy Tem VPN client app. 
publish_to: 'none' 

environment:
  sdk: ">=3.4.3 <4.0.0" 
dependencies:
  flutter:
    sdk: flutter

  openvpn_flutter: 
    path: ../ 
  
  get: ^4.6.6
  
  cupertino_icons: ^1.0.8

  http: ^1.2.1

  csv: ^6.0.0

  lottie: ^3.1.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0
 
flutter: 
  uses-material-design: true 

  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/