name: EasyTEM
description: Easy Tem VPN client app. 
publish_to: 'none' 

environment:
  sdk: ">=3.4.3 <4.0.0" 
dependencies:
  flutter:
    sdk: flutter

  openvpn_flutter: 
    path: ../ 
  
  get: ^4.6.6
  
  cupertino_icons: ^1.0.8

  http: ^1.2.1

  csv: ^6.0.0

  lottie: ^3.1.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0


dev_dependencies:
  flutter_launcher_icons: ^0.14.1
  flutter_test:
    sdk: flutter 
  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#ffffff" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/icon.png" # only available for Android 8.0 devices and above

 
flutter: 
  uses-material-design: true 

  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/